global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'spring-boot-server'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: 'user-service'
    metrics_path: /user-service/actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8000' ]

  - job_name: 'apigateway-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8000' ]



