server:
  port: 0


spring:
  application:
    name: user-service


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userservice?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update

    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      hibernate:
        default_batch_fetch_size: 10
        show-sql: true
        format_sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


greeting:
  message: welcome to the simple E-commerce


jwt:
  secret: dfsdfsdfdsfsdflkjflkadjfldkjfljflakjfaldsjffsadfdfadfdfalfjldfjaljfowjioholadfadlfhalkdhfald
  validationTime: 500



order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: B3
      produce: B3
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  endpoints:
    web:
      exposure:
        include: "*"


logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"